  sit_down: [ [ 0.20, 1.0, -2.49 ],
              [ -0.20, 1.0, -2.49 ],
              [ 0.20, 1.0, -2.49 ],
              [ -0.20, 1.0, -2.49 ] ]

  stand_up: [ [ 0.20, 0.7, -1.39 ],
              [ -0.20, 0.7, -1.39 ],
              [ 0.20, 0.7, -1.39 ],
              [ -0.20, 0.7, -1.39 ] ]

  give_paw: [ [ -0.30, 1.0, -1.39 ],
              [ -0.20, -0.6, -1.09 ],
              [ 0.20, 1.0, -2.39 ],
              [ -0.20, 1.0, -2.39 ] ]

  leg_spread: [ [ 1.20, 0.7, -1.39 ],
                [ -1.20, 0.7, -1.39 ],
                [ 1.20, 0.7, -1.39 ],
                [ -1.20, 0.7, -1.39 ] ]

  fl_leg: [ [ 0.20, -0.2, -1.09 ],
            [ -0.20, 0.7, -1.39 ],
            [ 0.20, 0.7, -1.39 ],
            [ -0.20, 0.7, -1.39 ] ]

  fr_leg: [ [ 0.20, 0.7, -1.09 ],
            [ -0.20, -0.2, -1.09 ],
            [ 0.20, 0.7, -1.39 ],
            [ -0.20, 0.7, -1.39 ] ]

  bow_forward: [ [ 0.20, 1.0, -1.79 ],
                 [ -0.20, 1.0, -1.79 ],
                 [ 0.20, 0.7, -1.29 ],
                 [ -0.20, 0.7, -1.29 ] ]

  leg_spread_left: [ [ 1.20, 0.7, -1.39 ],
                     [ 0.20, 0.7, -1.39 ],
                     [ 1.20, 0.7, -1.39 ],
                     [ 0.20, 0.7, -1.39 ] ]