# popi_control Settings -----------------------
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 100
  cycle_time_error_threshold: 0.05

# Settings for ros_control hardware interface
hardware_interface:
   joints:
      - joint1
      - joint2
   sim_control_mode: 0 # 0: position, 1: velocity

# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 50

joint1_eff_position_controller:
   type: effort_controllers/JointPositionController
   joint: joint1
   pid: {p: 100.0, i: 0.0, d: 1.0}
joint2_eff_position_controller:
   type: effort_controllers/JointPositionController
   joint: joint2
   pid: {p: 100.0, i: 0.0, d: 1.0}
